import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Banner from '../components/Banner'
import {API_URL} from '../../config/index'
import NewsItem from '../components/Newsitem'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ news }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Banner />
        <h1 className='my-5'>Latest News</h1>
        {news.length === 0 && <h3>No News</h3>}
        {news.map((item) => (
          <NewsItem key={item.id} news={item} />
        ))}
        {news.length > 0 && (
          <Link href="/news">
            <div className="btn">View All News</div>
          </Link>
        )}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`${API_URL}/api/news`);
  const news = await res.json();

  return {
    props: {
      news: news.slice(0, 5),
    },
  };
}

